package com.example.application.Backend;

import com.example.application.Backend.Film;
import com.example.application.Backend.FilmRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FilmRepository filmRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewFilm (@RequestParam String titel,
                                            @RequestParam String sprak,
                                            @RequestParam Integer langd,
                                            @RequestParam String aldersgrans,
                                            @RequestParam String genre) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Film f = new Film();
        f.setTitel(titel);
        f.setSprak(sprak);
        f.setLangd(langd);
        f.setAldersgrans(aldersgrans);
        f.setGenre(genre);
        filmRepository.save(f);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Film> getAllFilms() {
        // This returns a JSON or XML with the users
        return filmRepository.findAll();
    }
}